proceso:
    resource: "@ProcesoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_expertWelcome:
    pattern: /
    defaults: { _controller: ProcesoBundle:Expert:welcome }

_expertAddprocess:
    pattern: /addprocess
    defaults: { _controller: ProcesoBundle:Expert:addProcess }
    options:
        expose: true

_expertListProcessAct:
    pattern: /listprocessact
    defaults: { _controller: ProcesoBundle:Expert:listProcessActive }

_expertListProcessInactive:
    pattern: /listProcessInactive
    defaults: { _controller: ProcesoBundle:Expert:listProcessInactive }

_expertListTask:
    pattern: /listTask
    defaults: { _controller: ProcesoBundle:Expert:listTask }

_expertListResponsible:
    pattern: /listResponsible
    defaults: { _controller: ProcesoBundle:Expert:listResponsible}

_expertEditProcess:
    pattern: /editProcess/{id}
    defaults: { _controller: ProcesoBundle:Expert:editProcess}
    options:
        expose: true
