proceso:
    resource: "@ProcesoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#rutas de usurio experto
_expertAddprocess:
    pattern: /specialist/addprocess
    defaults: { _controller: ProcesoBundle:Expert:addProcess }
    options:
        expose: true

_expertActivity:
    pattern: /specialist/addActivity
    defaults: { _controller: ProcesoBundle:Expert:addActivity }
    options:
        expose: true

_expertListProcessAct:
    pattern: /specialist/listprocessact
    defaults: { _controller: ProcesoBundle:Expert:listProcessActive }

_expertListProcessInactive:
    pattern: /specialist/listProcessInactive
    defaults: { _controller: ProcesoBundle:Expert:listProcessInactive }

_expertListTask:
    pattern: /specialist/listTask
    defaults: { _controller: ProcesoBundle:Expert:listTask }

_expertListResponsible:
    pattern: /specialist/listResponsible
    defaults: { _controller: ProcesoBundle:Expert:listResponsible}

_expertActivityRelationship:
    pattern: /specialist/activityRelationship/{id}
    defaults: { _controller: ProcesoBundle:Expert:activityRelationship}
    options:
        expose: true

_expertEditProcess:
    pattern: /specialist/editProcess/{id}
    defaults: { _controller: ProcesoBundle:Expert:editProcess}
    options:
        expose: true

#rutas de login
tatiSoft_login:
    pattern:  /
    defaults: { _controller:  ProcesoBundle:Security\Security:login }

tatiSoft_login2:
    pattern:  /login
    defaults: { _controller:  ProcesoBundle:Security\Security:login }

tatiSoft_check:
    pattern:  /login_check
    defaults: { _controller:  ProcesoBundle:Security\Security:check }

tatiSoft_logout:
    pattern:  /logout
    defaults: { _controller:  ProcesoBundle:Security\Security:logout }

renderView:
    pattern:  /s
    defaults: { _controller: ProcesoBundle:Expert:renderViews }

#Runtas de usuario solicitantes
tatiSoft_soli_solicitante:
    pattern:  /solicitante/solicitar
    defaults: { _controller:  ProcesoBundle:Solicitante:holaSolicitante}

_tatiSoft_soli_solicitud:
    pattern:  /solicitante/solicitud
    defaults: { _controller:  ProcesoBundle:Solicitante:Requestprocess}
    options:
        expose: true

_tatiSoft_soli_upload:
    pattern:  /solicitante/subir
    defaults: { _controller:  ProcesoBundle:Solicitante:uploadFile}
    options:
        expose: true

_tatiSoft_soli_list:
    pattern:  /solicitante/listaSolicitudes
    defaults: { _controller:  ProcesoBundle:Solicitante:listRequest}
    options:
        expose: true

_tatiSoft_soli_files:
    pattern:  /solicitante/archivos
    defaults: { _controller:  ProcesoBundle:Solicitante:uploadedFiles}
    options:
        expose: true

_tatiSoft_soli_finished:
    pattern:  /solicitante/procesosFinalizados
    defaults: { _controller:  ProcesoBundle:Solicitante:finishedProcesses}
    options:
        expose: true

#rutas de usuario responsable

_tatiSoft_resp_list:
    pattern:  /responsable/actividadesPendientes
    defaults: { _controller:  ProcesoBundle:Responsable:pendingActivities}
    options:
        expose: true

_tatiSoft_resp_end_acitivity:
    pattern:  /responsable/actividadesTerminadas
    defaults: { _controller:  ProcesoBundle:Responsable:endActivities}
    options:
        expose: true

_tatiSoft_resp_file:
    pattern:  /responsable/archivos
    defaults: { _controller:  ProcesoBundle:Responsable:file}
    options:
        expose: true

_tatiSoft_resp_alert:
    pattern:  /responsable/alertas
    defaults: { _controller:  ProcesoBundle:Responsable:alert}
    options:
        expose: true