proceso:
    resource: "@ProcesoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


_portada:
    pattern: /prueba
    defaults: { _controller: ProcesoBundle:Default:prueba }
