proceso:
    resource: "@ProcesoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_adminWelcome:
    pattern: /
    defaults: { _controller: ProcesoBundle:Default:welcome }

_adminAddprocess:
    pattern: /addprocess
    defaults: { _controller: ProcesoBundle:Default:addProcess }

_adminListProcessAct:
    pattern: /listprocessact
    defaults: { _controller: ProcesoBundle:Default:listProcessActive }

_adminListProcessInactive:
    pattern: /listProcessInactive
    defaults: { _controller: ProcesoBundle:Default:listProcessInactive }

_adminListTask:
    pattern: /listTask
    defaults: { _controller: ProcesoBundle:Default:listTask }

_adminListRoles:
    pattern: /listRoles
    defaults: { _controller: ProcesoBundle:Default:listRoles }
