security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ESPECIALISTA_READ: ROLE_ESPECIALISTA_READ
        ROLE_ESPECIALISTA_UPDATE: ROLE_ESPECIALISTA_READ
        ROLE_ESPECIALISTA_CREATE_ALL: ROLE_ESPECIALISTA_UPDATE
        ROLE_SOLICITANTE: ROLE_SOLICITANTE
        ROLE_RESPONSABLE_READ: ROLE_RESPONSABLE_READ
        ROLE_RESPONSABLE_UPDATE: ROLE_RESPONSABLE_READ
        ROLE_AUTORIDAD: ROLE_AUTORIDAD

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                csrf_provider: form.csrf_provider
                default_target_path: renderView

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

        #Rutas permitidad para el usuario especialista
        - { path: ^/specialist/addprocess, role: ROLE_ESPECIALISTA_CREATE_ALL }
        - { path: ^/specialist/listprocessact, role: ROLE_ESPECIALISTA_READ }
        - { path: ^/specialist/listTask, role: ROLE_ESPECIALISTA_READ }
        - { path: ^/specialist/listResponsible, role: ROLE_ESPECIALISTA_READ }
        - { path: ^/specialist/editProcess, role: ROLE_ESPECIALISTA_UPDATE }
        #Rutas permitidas para el usuario solicitante
        - { path: ^/solicitante/solicitar, role: ROLE_SOLICITANTE}
        - { path: ^/solicitante/solicitud, role: ROLE_SOLICITANTE}
        - { path: ^/solicitante/listaSolicitudes, role: ROLE_SOLICITANTE}
        - { path: ^/solicitante/archivos, role: ROLE_SOLICITANTE}
        - { path: ^/solicitante/procesosFinalizados, role: ROLE_SOLICITANTE}
        #Rutas permitidas para el usuario responsable
        - { path: ^/responsable/actividadesPendientes, role: ROLE_RESPONSABLE_UPDATE}
        - { path: ^/responsable/actividadesTerminadas, role: ROLE_RESPONSABLE_UPDATE}
        - { path: ^/responsable/archivos, role: ROLE_RESPONSABLE_UPDATE}
        - { path: ^/responsable/alertas, role: ROLE_RESPONSABLE_UPDATE}