services:
    InformationService:
        class: Tati\ProcesoBundle\Resources\Services\InformationService
        arguments: ["@doctrine.orm.entity_manager"]

    RequestService:
        class: Tati\ProcesoBundle\Resources\Services\RequestService
        arguments: ["@doctrine.orm.entity_manager"]

    AdminService:
        class: Tati\ProcesoBundle\Resources\Services\AdminService
        arguments: ["@doctrine.orm.entity_manager"]

    GeneralService:
        class: Tati\ProcesoBundle\Resources\Services\GeneralService
        arguments: ["@doctrine.orm.entity_manager"]